In [ ]:
import sys
import pandas as pd
import numpy as np

path = 'dataC.csv'

In [ ]:

df = pd.read_csv(path)
df.count()
df.head()

,Severity,State,Precipitation,Windy,Start_Lat,Start_Lng,Date,Time
0,2,FL,0.000000,0,-82.133198,28.032354,2022-04-07,2022-04-07 16:31:58
1,2,MA,0.000000,0,-71.123199,42.368259,2019-08-23,2019-08-23 08:19:46
2,2,NC,0.000000,0,-80.845690,35.215000,2020-05-26,2020-05-26 09:04:00
3,2,LA,0.000000,0,-91.145409,30.521433,2019-11-22,2019-11-22 14:39:39
4,2,NY,1.377695,0,-73.593292,41.356518,2016-07-16,2016-07-16 17:55:46

## Identification of precipitation and windy conditions representing approximately 5% of the dataset using masking for optimazation of Oracle

In [13]:

result = df[df['Windy']==0].groupby('Precipitation').count().sort_values(by='Windy', ascending=False).head(35)
print(result)

               Severity   State   Windy  Start_Lat  Start_Lng    Date    Time
Precipitation
0.000000         596814  596814  596814     596814     596814  596814  596814
1.377695         254408  254408  254408     254408     254408  254408  254408
1.638706          46189   46189   46189      46189      46189   46189   46189
11.470945          2355    2355    2355       2355       2355    2355    2355
14.748357          1694    1694    1694       1694       1694    1694    1694
16.387064          1395    1395    1395       1395       1395    1395    1395
18.025770          1208    1208    1208       1208       1208    1208    1208
19.664478          1066    1066    1066       1066       1066    1066    1066
21.303184           926     926     926        926        926     926     926
22.941889           828     828     828        828        828     828     828
24.580595           688     688     688        688        688     688     688
26.219303           600     600     600        600        600     600     600
27.858009           569     569     569        569        569     569     569
29.496715           492     492     492        492        492     492     492
31.135423           425     425     425        425        425     425     425
32.774128           411     411     411        411        411     411     411
34.412834           368     368     368        368        368     368     368
37.690248           291     291     291        291        291     291     291
39.328956           282     282     282        282        282     282     282
40.967659           241     241     241        241        241     241     241
42.606367           232     232     232        232        232     232     232
44.245071           221     221     221        221        221     221     221
45.883779           213     213     213        213        213     213     213
50.799898           163     163     163        163        163     163     163
47.522487           161     161     161        161        161     161     161
52.438606           156     156     156        156        156     156     156
49.161190           151     151     151        151        151     151     151
57.354726           131     131     131        131        131     131     131
58.993429           117     117     117        117        117     117     117
55.716018           111     111     111        111        111     111     111
54.077310           106     106     106        106        106     106     106
62.270845           100     100     100        100        100     100     100
63.909549            99      99      99         99         99      99      99
60.632137            92      92      92         92         92      92      92
65.548257            75      75      75         75         75      75      75

In [14]:
## Values for dataset A
##values = [42.606367, 11.470945, 9.832239, 8.193532,
  ##       6.554826, 4.916119, 3.277413]
## Values for dataset B
##values = [36.051540, 13.109652, 9.832239, 8.193532,
  ##        6.554826, 4.916119, 3.277413]
## Values for dataset C
values = [58.993429, 55.716018]

mask = np.isclose(df["Precipitation"].values[:, None], values).any(axis=1)
df.loc[mask, "Precipitation"] = 1.638706

In [16]:
df["Precipitation"] = df["Precipitation"].round(6)

In [17]:

result = df[df['Windy']==0].groupby(df["Precipitation"]).count().sort_values(by='Windy', ascending=False).head(35)
print(result)

               Severity   State  Precipitation   Windy  Start_Lat  Start_Lng  \
Precipitation
0.000000         596814  596814         596814  596814     596814     596814
1.377695         254408  254408         254408  254408     254408     254408
1.638706          46417   46417          46417   46417      46417      46417
11.470945          2355    2355           2355    2355       2355       2355
14.748357          1694    1694           1694    1694       1694       1694
16.387064          1395    1395           1395    1395       1395       1395
18.025770          1208    1208           1208    1208       1208       1208
19.664478          1066    1066           1066    1066       1066       1066
21.303184           926     926            926     926        926        926
22.941889           828     828            828     828        828        828
24.580595           688     688            688     688        688        688
26.219303           600     600            600     600        600        600
27.858009           569     569            569     569        569        569
29.496715           492     492            492     492        492        492
31.135423           425     425            425     425        425        425
32.774128           411     411            411     411        411        411
34.412834           368     368            368     368        368        368
37.690248           291     291            291     291        291        291
39.328956           282     282            282     282        282        282
40.967659           241     241            241     241        241        241
42.606367           232     232            232     232        232        232
44.245071           221     221            221     221        221        221
45.883779           213     213            213     213        213        213
50.799898           163     163            163     163        163        163
47.522487           161     161            161     161        161        161
52.438606           156     156            156     156        156        156
49.161190           151     151            151     151        151        151
57.354726           131     131            131     131        131        131
54.077310           106     106            106     106        106        106
62.270845           100     100            100     100        100        100
63.909549            99      99             99      99         99         99
60.632137            92      92             92      92         92         92
65.548257            75      75             75      75         75         75
68.825668            68      68             68      68         68         68
67.186960            68      68             68      68         68         68

                 Date    Time
Precipitation
0.000000       596814  596814
1.377695       254408  254408
1.638706        46417   46417
11.470945        2355    2355
14.748357        1694    1694
16.387064        1395    1395
18.025770        1208    1208
19.664478        1066    1066
21.303184         926     926
22.941889         828     828
24.580595         688     688
26.219303         600     600
27.858009         569     569
29.496715         492     492
31.135423         425     425
32.774128         411     411
34.412834         368     368
37.690248         291     291
39.328956         282     282
40.967659         241     241
42.606367         232     232
44.245071         221     221
45.883779         213     213
50.799898         163     163
47.522487         161     161
52.438606         156     156
49.161190         151     151
57.354726         131     131
54.077310         106     106
62.270845         100     100
63.909549          99      99
60.632137          92      92
65.548257          75      75
68.825668          68      68
67.186960          68      68

## Identification of severity and windy conditions representing approximately 5% of the dataset using masking for optimazation of Postgre and MongoDB

In [18]:
result = df[df['Windy']==0].groupby('Severity').count().sort_values(by='Windy', ascending=False).head(35)
print(result)

           State  Precipitation   Windy  Start_Lat  Start_Lng    Date    Time
Severity
2         734790         734790  734790     734790     734790  734790  734790
3         103902         103902  103902     103902     103902  103902  103902
4          68368          68368   68368      68368      68368   68368   68368
1           8055           8055    8055       8055       8055    8055    8055

In [ ]:

#workload A
#head(90835)
#workload B
#head(44760)
#subset_idx = df[(df["Windy"] == 0) & (df["Severity"] == 4)].head(44760).index
#df.loc[subset_idx, "Severity"] = 3

#workload C
#subset_idx = df[(df["Windy"] == 0) & (df["Severity"] == 4)].head(21952).index
#df.loc[subset_idx, "Severity"] = 3

In [27]:

result = df[df['Windy']==0].groupby('Severity').count().sort_values(by='Windy', ascending=False).head(35)
print(result)

           State  Precipitation   Windy  Start_Lat  Start_Lng    Date    Time
Severity
2         734790         734790  734790     734790     734790  734790  734790
3         125854         125854  125854     125854     125854  125854  125854
4          46416          46416   46416      46416      46416   46416   46416
1           8055           8055    8055       8055       8055    8055    8055

## Crosstabulation used to identify state and severity combinations representing approximately 5% of the dataset for the basic dataset

In [32]:
table = pd.crosstab(df["State"], df["Severity"])
print(table)

Severity     1       2      3     4
State
AL          89    9248   2161   677
AR           1    2262    137   231
AZ         943   16769   1786   882
CA        1299  173059  26788  7486
CO         131    6929   2851  1196
CT           8    6201   1767   741
DC          14    1987    121    91
DE          24    1423    123   168
FL         829   91394  10627  3483
GA         113   11372   6392  2588
IA           3    2050    720   327
ID           0    1191     35    53
IL         208   13201   5810  1759
IN          39    5490   1665   829
KS           1    1702    394   154
KY          37    2203   1282   417
LA         267   15525   1789   565
MA         173    4939   1908   507
MD          48   10256   2193  1305
ME           2     290     34    16
MI         101   13870   4254  1612
MN          69   19210   2997   765
MO          37    5647   2590   810
MS           2    1263    359   177
MT           0    3223     23    42
NC         678   36221   3103  1672
ND           0     379      4     2
NE           8    3012    420   159
NH          11     940    206    59
NJ          28   13082   2202   998
NM          19     812    307   133
NV          11    2045    406   172
NY         148   32961   7126  2615
OH         203    9856   3259  1324
OK         155    9404    637   196
OR         146   19750   1179   749
PA         214   29681   3522  2163
RI          22    1067    769   158
SC         746   46411   4235  1259
SD           0      23      2     6
TN         295   16466   2953   987
TX         475   54462  11758  3379
UT          69    8862   1523   458
VA         358   26650    536  1563
VT           0       0     22    12
WA         114    8903   3076  1088
WI           8    2688   1091   589
WV           0    1503     72   108
WY           0     273     29    59

In [31]:
#Workload A:

#Workload B:
#mask = (df["State"] == "MO") & (df["Severity"] == 2)
#df.loc[mask, "State"] = "SC"
#df.loc[mask, "Severity"] = 2
#mask = (df["State"] == "NC") & (df["Severity"] == 1)
#df.loc[mask, "State"] = "SC"
#df.loc[mask, "Severity"] = 2


#mask = (df["State"] == "MO") & (df["Severity"] == 2)
#df.loc[mask, "State"] = "SC"
#df.loc[mask, "Severity"] = 2

#mask = (df["State"] == "NC") & (df["Severity"] == 1)
#df.loc[mask, "State"] = "SC"
#df.loc[mask, "Severity"] = 2

#Workload C:
msk = (df["State"] == "ME") & (df["Severity"] == 2)
df.loc[mask, "State"] = "SC"
df.loc[mask, "Severity"] = 2
mask = (df["State"] == "VT") & (df["Severity"] == 2)
df.loc[mask, "State"] = "SC"
df.loc[mask, "Severity"] = 2

In [33]:
#df = df.drop('Unnamed: 0', axis=1)
df.head()

,Severity,State,Precipitation,Windy,Start_Lat,Start_Lng,Date,Time
0,2,FL,0.000000,0,-82.133198,28.032354,2022-04-07,2022-04-07 16:31:58
1,2,MA,0.000000,0,-71.123199,42.368259,2019-08-23,2019-08-23 08:19:46
2,2,NC,0.000000,0,-80.845690,35.215000,2020-05-26,2020-05-26 09:04:00
3,2,LA,0.000000,0,-91.145409,30.521433,2019-11-22,2019-11-22 14:39:39
4,2,NY,1.377695,0,-73.593292,41.356518,2016-07-16,2016-07-16 17:55:46

## Save changes to csv file

In [ ]:
df.to_csv(path, index = False)

## To find geographic bounderies that contain ~5% of rows

In [5]:

df['lat_bin'] = (df['Start_Lat'] * 50).astype(int)
df['lon_bin'] = (df['Start_Lng'] * 50).astype(int)


grid = df.groupby(['lat_bin', 'lon_bin']).size().unstack(fill_value=0)
matrix = grid.values


prefix = matrix.cumsum(axis=0).cumsum(axis=1)

def rect_sum(x1, y1, x2, y2):
    total = prefix[x2, y2]
    if x1 > 0:
        total -= prefix[x1-1, y2]
    if y1 > 0:
        total -= prefix[x2, y1-1]
    if x1 > 0 and y1 > 0:
        total += prefix[x1-1, y1-1]
    return total

target = int(len(df) * 0.05)

cells = []
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        if matrix[i, j] > 0:
            cells.append((matrix[i, j], i, j))

cells.sort(reverse=True)

best = None

for _, cx, cy in cells[:200]:  
    
    for size in range(1, 100):  
        
        x1 = max(0, cx - size)
        y1 = max(0, cy - size)
        x2 = min(matrix.shape[0]-1, cx + size)
        y2 = min(matrix.shape[1]-1, cy + size)

        s = rect_sum(x1, y1, x2, y2)

        if s >= target:
            area = (x2 - x1) * (y2 - y1)

            if best is None or area < best['area']:
                best = {
                    'x1': x1, 'y1': y1,
                    'x2': x2, 'y2': y2,
                    'sum': s,
                    'area': area
                }
            break  

print(best)

lat_values = grid.index.values
lon_values = grid.columns.values

min_lat = lat_values[x1] / 50
max_lat = lat_values[x2] / 50

min_lon = lon_values[y1] / 50
max_lon = lon_values[y2] / 50

print(min_lat)
print(max_lat)
print(min_lon)
print(max_lon)

{'x1': 309, 'y1': 458, 'x2': 333, 'y2': 482, 'sum': 95168, 'area': 576}
-99.68
-95.72
28.34
32.3

## To find the time bounds for ~5% of dataset

In [7]:
df['time_part'] = df['Time'].str.split(' ').str[1]
df['hour'] = df['time_part'].str.split(':').str[0].astype(int)
df['minute'] = df['time_part'].str.split(':').str[1].astype(int)
df['minute_index'] = df['hour'] * 60 + df['minute']

histogram = df['minute_index'].value_counts().sort_index()
histogram = histogram.reindex(range(1440), fill_value=0).values

total = len(df)
target = total * 0.05

left = 0
current_sum = 0
best = None

for right in range(1440):
    current_sum += histogram[right]

    while current_sum >= target:
        if best is None or (right - left) < (best['right'] - best['left']):
            best = {'left': left, 'right': right, 'sum': current_sum}
        current_sum -= histogram[left]
        left += 1


def to_time(idx):
    h = idx // 60
    m = idx % 60
    return f"{h:02d}:{m:02d}:00"

result = {
    'total_rows': total,
    'target_rows': target,
    'actual_rows': best['sum'],
    'start_time': to_time(best['left']),
    'end_time': to_time(best['right'])
}

print(result)

{'total_rows': 928333, 'target_rows': 46416.65, 'actual_rows': 46448, 'start_time': '17:52:00', 'end_time': '18:29:00'}